### ISSUE TITLE
Not support the windows platform

### ISSUE THREAD

**Issue by mato533** [fossamagna/google-script-dts-generator#199]
When use this library on windows platform, All source code file is ignored.
As a result, IRun interface have only native method of google.script.run. It does not include methods that i have created.

The root cause is The node-glob treat the backslash as the escape character.

**Comment by fossamagna** [comment]
@mato533 I published [google-script-dts-generator@1.3.1](https://www.npmjs.com/package/google-script-dts-generator/v/1.3.1). check it please.
